-- Reuse locked_by/locked_until from 0001 as the unique claim token and lease.
-- Persist insertion order so events with identical timestamps remain ordered.
ALTER TABLE outbox_events ADD COLUMN delivery_order BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH ordered AS (
    SELECT event_id, row_number() OVER (ORDER BY occurred_at, event_id) AS position
    FROM outbox_events
)
UPDATE outbox_events e SET delivery_order = ordered.position
FROM ordered WHERE ordered.event_id = e.event_id;
ALTER TABLE outbox_events ALTER COLUMN delivery_order SET GENERATED ALWAYS;
SELECT setval(pg_get_serial_sequence('outbox_events', 'delivery_order'),
    COALESCE((SELECT max(delivery_order) FROM outbox_events), 1),
    EXISTS (SELECT 1 FROM outbox_events));

ALTER TABLE outbox_events ADD COLUMN wallet_id TEXT
    GENERATED ALWAYS AS (payload->'data'->>'walletId') STORED;
ALTER TABLE outbox_events ADD CONSTRAINT outbox_wallet_required
    CHECK (wallet_id IS NOT NULL AND btrim(wallet_id) <> '');
CREATE INDEX outbox_wallet_pending_order ON outbox_events(wallet_id, delivery_order)
    WHERE published_at IS NULL;

CREATE FUNCTION protect_outbox_delivery_order() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.delivery_order IS DISTINCT FROM OLD.delivery_order THEN
        RAISE EXCEPTION 'outbox delivery order is immutable' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER outbox_delivery_order_immutable BEFORE UPDATE ON outbox_events
    FOR EACH ROW EXECUTE FUNCTION protect_outbox_delivery_order();
